spring:
  application:
    name: PRODUCT_SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

server:
  port: 5555